keycloak:
  adminUser: admin
  adminPassword: "<a strong password>"

ingress:
  enabled: true
  className: public
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
  hosts:
    - host: keycloak.machasing.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - keycloak.machasing.com
      secretName: keycloak-tls

# Wichtig f√ºr Betrieb hinter Reverse Proxy / Ingress (TLS-Termination am Ingress)
extraEnv:
  KC_HOSTNAME_URL: "https://keycloak.machasing.com"
  KC_PROXY_HEADERS: "xforwarded"
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"

